# Generated by Django 3.2 on 2021-07-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
